export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";


export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";


export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";


export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";



export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";



export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";



export const CLEAR_ERRORS = "CLEAR_ERRORS";


export const ALL_ORLIST_REQUEST = "ALL_ORLIST_REQUEST";
export const ALL_ORLIST_SUCCESS = "ALL_ORLIST_SUCCESS";
export const ALL_ORLIST_FAIL = "ALL_ORLIST_FAIL";


export const OR_DETAILS_REQUEST = "OR_DETAILS_REQUEST";
export const OR_DETAILS_SUCCESS = "OR_DETAILS_SUCCESS";
export const OR_DETAILS_FAIL = "OR_DETAILS_FAIL";


export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";
export const UPDATE_STATUS_RESET = "UPDATE_STATUS_RESET";


export const ALL_TOKEN_REQUEST = "ALL_TOKEN_REQUEST";
export const ALL_TOKEN_SUCCESS = "ALL_TOKEN_SUCCESS";
export const ALL_TOKEN_FAIL = "ALL_TOKEN_FAIL";



export const TOKEN_DETAILS_REQUEST = "TOKEN_DETAILS_REQUEST";
export const TOKEN_DETAILS_SUCCESS = "TOKEN_DETAILS_SUCCESS";
export const TOKEN_DETAILS_FAIL = "TOKEN_DETAILS_FAIL";


export const UPDATE_TOKEN_REQUEST = "UPDATE_TOKEN_REQUEST";
export const UPDATE_TOKEN_SUCCESS = "UPDATE_TOKEN_SUCCESS";
export const UPDATE_TOKEN_FAIL = "UPDATE_TOKEN_FAIL";
export const UPDATE_TOKEN_RESET = "UPDATE_TOKEN_RESET";


export const PLICL_TOKEN_REQUEST = "PLICL_TOKEN_REQUEST";
export const PLICL_TOKEN_SUCCESS = "PLICL_TOKEN_SUCCESS";
export const PLICL_TOKEN_FAIL = "PLICL_TOKEN_FAIL";

